name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Update version in pom.xml
      run: mvn versions:set -DnewVersion=${{ steps.extract_version.outputs.VERSION }}

    - name: Run tests
      run: mvn clean test

    - name: Build and package
      run: mvn clean package -DskipTests

    - name: Generate JavaDoc
      run: mvn javadoc:javadoc

    - name: Create sources JAR
      run: mvn source:jar

    - name: Create JavaDoc JAR
      run: mvn javadoc:jar

    - name: Create release notes
      id: release_notes
      run: |
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
        echo "## JPWise v${{ steps.extract_version.outputs.VERSION }}" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "### Changes" >> $GITHUB_OUTPUT
        # Get all tags and find the previous one
        PREV_TAG=$(git tag --sort=-version:refname | grep -v "^v${{ steps.extract_version.outputs.VERSION }}$" | head -n 1 || echo "")
        if [ -n "$PREV_TAG" ]; then
          echo "Changes since $PREV_TAG:" >> $GITHUB_OUTPUT
          git log --pretty=format:"- %s" $PREV_TAG..HEAD >> $GITHUB_OUTPUT
        else
          echo "- Initial release of JPWise v${{ steps.extract_version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          echo "- Java Pairwise Testing Framework with support for complex parameter relationships" >> $GITHUB_OUTPUT
          echo "- Comprehensive API with fluent builder pattern and direct generation methods" >> $GITHUB_OUTPUT
          echo "- TestNG DataProvider integration for seamless test automation" >> $GITHUB_OUTPUT
          echo "- Multiple partition types: SimpleValue, GenericPartition, CyclingPartition" >> $GITHUB_OUTPUT
          echo "- Modern Java 11+ compatibility with enhanced documentation" >> $GITHUB_OUTPUT
        fi
        echo "" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.extract_version.outputs.VERSION }}
        name: JPWise v${{ steps.extract_version.outputs.VERSION }}
        body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
        draft: false
        prerelease: false
        files: |
          target/jpwise-${{ steps.extract_version.outputs.VERSION }}.jar
          target/jpwise-${{ steps.extract_version.outputs.VERSION }}-sources.jar
          target/jpwise-${{ steps.extract_version.outputs.VERSION }}-javadoc.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Update version in pom.xml
      run: mvn versions:set -DnewVersion=${{ steps.extract_version.outputs.VERSION }}

    - name: Build and test
      run: mvn clean compile test

    - name: Publish to GitHub Packages
      run: mvn deploy -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 